global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel_collector
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:4317"]
  - job_name: "fluent-bit"
    static_configs:
      - targets: ["fluent-bit:2020"]
