apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc/
            - name: docker-logs
              mountPath: /var/lib/docker/containers/
      volumes:
        - name: config-volume
          configMap:
            name: fluent-bit-config
        - name: docker-logs
          hostPath:
            path: /var/lib/docker/containers/
